spring.application.name=did-qr-verifier
spring.web.resources.static-locations=classpath:/static/,file:./qr/
server.address=0.0.0.0

# h2 database
spring.h2.console.enabled=true
spring.h2.console.path=/db
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# file max size - 10MB / tomcat max szie - 15MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=15MB

# blockchain setting
blockchain.rpc-url=http://127.0.0.1:7545
blockchain.private-key=0xda620118ce91a58c42644dc29c28a9313ee0380a73e57c624b1e417f25e3d5ec
blockchain.contract-address=0x030808d282430637f5201cea198d0ba035db6ae4